name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awscli

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker images
      run: |
        docker-compose build
        docker images  # This will list all built images

    - name: Tag Docker images
      run: |
        docker tag kanban-app 349224041754.dkr.ecr.eu-west-1.amazonaws.com/backend_kanban:1.0.4
        docker tag kanban-ui 349224041754.dkr.ecr.eu-west-1.amazonaws.com/frontend_kanban:1.0.4

    - name: Push Docker images to ECR
      run: |
        docker push 349224041754.dkr.ecr.eu-west-1.amazonaws.com/backend_kanban:1.0.4
        docker push 349224041754.dkr.ecr.eu-west-1.amazonaws.com/frontend_kanban:1.0.4
